import {
	DecodeError, Readable, EncodeError, Duplexer, DuplexerLookupTable, Writable,
} from "./stream";
import {
	Empty, NotImplemented, Bool, UInt8, UInt16, UInt32, BufferT,
	SpaceOptimizedUInt16, SpaceOptimizedUInt32, StringT, Utf8String,
} from "./types";
import { Direction, MapPosition, DisconnectReason } from "./data";


export type CrcData = { crc: number, tickOfCrc: number };
export const CrcData: Duplexer<CrcData> = {
	read(stream: Readable) {
		return {
			crc: UInt32.read(stream),
			tickOfCrc: UInt32.read(stream),
		};
	},
	write(stream: Writable, data: CrcData) {
		UInt32.write(stream, data.crc);
		UInt32.write(stream, data.tickOfCrc);
	},
};

export enum ShootingStateState {
	NotShooting,
	ShootingEnemies,
	ShootingSelected,
}
export type ShootingState = { state: ShootingStateState, target: MapPosition };
export const ShootingState: Duplexer<ShootingState> = {
	read(stream: Readable) {
		return {
			state: UInt8.read(stream),
			target: MapPosition.read(stream),
		};
	},
	write(stream: Writable, state: ShootingState) {
		UInt8.write(stream, state.state);
		MapPosition.write(stream, state.target);
	},
};

export type PlayerJoinGameData = {
	peerID: number,
	playerIndex: number,
	forceID: number,
	username: string,
	asEditor: boolean,
	admin: boolean,
}
export const PlayerJoinGameData: Duplexer<PlayerJoinGameData> = {
	read(stream: Readable) {
		return {
			peerID: SpaceOptimizedUInt16.read(stream),
			playerIndex: UInt16.read(stream),
			forceID: UInt8.read(stream),
			username: Utf8String.read(stream),
			asEditor: Bool.read(stream),
			admin: Bool.read(stream),
		};
	},
	write(stream: Writable, data: PlayerJoinGameData) {
		SpaceOptimizedUInt16.write(stream, data.peerID);
		UInt16.write(stream, data.playerIndex);
		UInt8.write(stream, data.forceID);
		Utf8String.write(stream, data.username);
		Bool.write(stream, data.asEditor);
		Bool.write(stream, data.admin);
	},
};

export type ServerCommandData = {
	command: Buffer,
	id: number,
	connectionID: Buffer,
}
export const ServerCommandData: Duplexer<ServerCommandData> = {
	read(stream: Readable) {
		return {
			command: StringT.read(stream),
			id: UInt32.read(stream),
			connectionID: BufferT.read(stream, 8),
		};
	},
	write(stream: Writable, data: ServerCommandData) {
		StringT.write(stream, data.command);
		UInt32.write(stream, data.id);
		BufferT.write(stream, data.connectionID);
	},
};


export enum InputActionType {
	Nothing,
	StopWalking,
	BeginMining,
	StopMining,
	ToggleDriving,
	OpenGui,
	CloseGui,
	OpenCharacterGui,
	OpenCurrentVehicleGui,
	ConnectRollingStock,
	DisconnectRollingStock,
	SelectedEntityCleared,
	ClearCursor,
	ResetAssemblingMachine,
	OpenTechnologyGui,
	LaunchRocket,
	OpenProductionGui,
	StopRepair,
	CancelNewBlueprint,
	CloseBlueprintRecord,
	CopyEntitySettings,
	PasteEntitySettings,
	DestroyOpenedItem,
	CopyOpenedItem,
	ToggleShowEntityInfo,
	SingleplayerInit,
	MultiplayerInit,
	DisconnectAllPlayers,
	SwitchToRenameStopGui,
	OpenBonusGui,
	OpenTrainsGui,
	OpenAchievementsGui,
	CycleBlueprintBookForwards,
	CycleBlueprintBookBackwards,
	CycleClipboardForwards,
	CycleClipboardBackwards,
	StopMovementInTheNextTick,
	ToggleEnableVehicleLogisticsWhileMoving,
	ToggleDeconstructionItemEntityFilterMode,
	ToggleDeconstructionItemTileFilterMode,
	OpenLogisticGui,
	SelectNextValidGun,
	ToggleMapEditor,
	DeleteBlueprintLibrary,
	GameCreatedFromScenario,
	ActivateCopy,
	ActivateCut,
	ActivatePaste,
	Undo,
	TogglePersonalRoboport,
	ToggleEquipmentMovementBonus,
	TogglePersonalLogisticRequests,
	ToggleEntityLogisticRequests,
	StopBuildingByMoving,
	FlushOpenedEntityFluid,
	ForceFullCRC,

	OpenTipsAndTricksGui,
	OpenBlueprintLibraryGui,
	ChangeBlueprintLibraryTab,
	DropItem,
	Build,
	StartWalking,
	BeginMiningTerrain,
	ChangeRidingState,
	OpenItem,
	OpenParentOfOpenedItem,
	ResetItem,
	DestroyItem,
	OpenModItem,
	OpenEquipment,
	CursorTransfer,
	CursorSplit,
	StackTransfer,
	InventoryTransfer,
	CheckCRCHeuristic,
	Craft,
	WireDragging,
	ChangeShootingState,
	SetupAssemblingMachine,
	SelectedEntityChanged,
	SmartPipette,
	StackSplit,
	InventorySplit,
	CancelCraft,
	SetFilter,
	CheckCRC,
	SetCircuitCondition,
	SetSignal,
	StartResearch,
	SetLogisticFilterItem,
	SetLogisticFilterSignal,
	SetCircuitModeOfOperation,
	GuiClick,
	GuiConfirmed,
	WriteToConsole,
	MarketOffer,
	AddTrainStation,
	ChangeTrainStopStation,
	ChangeActiveItemGroupForCrafting,
	ChangeActiveItemGroupForFilters,
	ChangeActiveCharacterTab,
	GuiTextChanged,
	GuiCheckedStateChanged,
	GuiSelectionStateChanged,
	GuiSelectedTabChanged,
	GuiValueChanged,
	GuiSwitchStateChanged,
	GuiLocationChanged,
	PlaceEquipment,
	TakeEquipment,
	UseItem,
	SendSpidertron,
	UseArtilleryRemote,
	SetInventoryBar,
	MoveOnZoom,
	StartRepair,
	Deconstruct,
	Upgrade,
	Copy,
	AlternativeCopy,
	SelectBlueprintEntities,
	AltSelectBlueprintEntities,
	SetupBlueprint,
	SetupSingleBlueprintRecord,
	CopyOpenedBlueprint,
	ReassignBlueprint,
	OpenBlueprintRecord,
	GrabBlueprintRecord,
	DropBlueprintRecord,
	DeleteBlueprintRecord,
	UpgradeOpenedBlueprintByRecord,
	UpgradeOpenedBlueprintByItem,
	SpawnItem,
	SpawnItemStackTransfer,
	UpdateBlueprintShelf,
	TransferBlueprint,
	TransferBlueprintImmediately,
	EditBlueprintToolPreview,
	RemoveCables,
	ExportBlueprint,
	ImportBlueprint,
	ImportBlueprintsFiltered,
	PlayerJoinGame,
	PlayerAdminChange,
	CancelDeconstruct,
	CancelUpgrade,
	ChangeArithmeticCombinatorParameters,
	ChangeDeciderCombinatorParameters,
	ChangeProgrammableSpeakerParameters,
	ChangeProgrammableSpeakerAlertParameters,
	ChangeProgrammableSpeakerCircuitParameters,
	SetVehicleAutomaticTargetingParameters,
	BuildTerrain,
	ChangeTrainWaitCondition,
	ChangeTrainWaitConditionData,
	CustomInput,
	ChangeItemLabel,
	ChangeItemDescription,
	ChangeEntityLabel,
	BuildRail,
	CancelResearch,
	SelectArea,
	AltSelectArea,
	ReverseSelectArea,
	ServerCommand,
	SetControllerLogisticTrashFilterItem,
	SetEntityLogisticTrashFilterItem,
	SetInfinityContainerFilterItem,
	SetInfinityPipeFilter,
	ModSettingsChanged,
	SetEntityEnergyProperty,
	EditCustomTag,
	EditPermissionGroup,
	ImportBlueprintString,
	ImportPermissionsString,
	ReloadScript,
	ReloadScriptDataTooLarge,
	GuiElemChanged,
	BlueprintTransferQueueUpdate,
	DragTrainSchedule,
	DragTrainWaitCondition,
	SelectItem,
	SelectEntitySlot,
	SelectTileSlot,
	SelectMapperSlot,
	DisplayResolutionChanged,
	QuickBarSetSlot,
	QuickBarPickSlot,
	QuickBarSetSelectedPage,
	PlayerLeaveGame,
	MapEditorAction,
	PutSpecialItemInMap,
	PutSpecialRecordInMap,
	ChangeMultiplayerConfig,
	AdminAction,
	LuaShortcut,
	TranslateString,
	FlushOpenedEntitySpecificFluid,
	ChangePickingState,
	SelectedEntityChangedVeryClose,
	SelectedEntityChangedVeryClosePrecise,
	SelectedEntityChangedRelative,
	SelectedEntityChangedBasedOnUnitNumber,
	SetAutosortInventory,
	SetFlatControllerGui,
	SetRecipeNotifications,
	SetAutoLaunchRocket,
	SwitchConstantCombinatorState,
	SwitchPowerSwitchState,
	SwitchInserterFilterModeState,
	SwitchConnectToLogisticNetwork,
	SetBehaviorMode,
	FastEntityTransfer,
	RotateEntity,
	FastEntitySplit,
	SetTrainStopped,
	ChangeControllerSpeed,
	SetAllowCommands,
	SetResearchFinishedStopsGame,
	SetInserterMaxStackSize,
	OpenTrainGui,
	SetEntityColor,
	SetDeconstructionItemTreesAndRocksOnly,
	SetDeconstructionItemTileSelectionMode,
	DeleteCustomTag,
	DeletePermissionGroup,
	AddPermissionGroup,
	SetInfinityContainerRemoveUnfilteredItems,
	SetCarWeaponsControl,
	SetRequestFromBuffers,
	ChangeActiveQuickBar,
	OpenPermissionsGui,
	DisplayScaleChanged,
	SetSplitterPriority,
	GrabInternalBlueprintFromText,
	SetHeatInterfaceTemperature,
	SetHeatInterfaceMode,
	OpenTrainStationGui,
	RemoveTrainStation,
	GoToTrainStation,
	RenderModeChanged,
	SetPlayerColor,
	PlayerClickedGpsTag,
	SetTrainsLimit,
	ClearRecipeNotification,
	SetLinkedContainerLinkID,
}

export type InputActionValueType = {
	[InputActionType.Nothing]: Empty,
	[InputActionType.StopWalking]: Empty,
	[InputActionType.BeginMining]: Empty,
	[InputActionType.StopMining]: Empty,
	[InputActionType.ToggleDriving]: Empty,
	[InputActionType.OpenGui]: Empty,
	[InputActionType.CloseGui]: Empty,
	[InputActionType.OpenCharacterGui]: Empty,
	[InputActionType.OpenCurrentVehicleGui]: Empty,
	[InputActionType.ConnectRollingStock]: Empty,
	[InputActionType.DisconnectRollingStock]: Empty,
	[InputActionType.SelectedEntityCleared]: Empty,
	[InputActionType.ClearCursor]: Empty,
	[InputActionType.ResetAssemblingMachine]: Empty,
	[InputActionType.OpenTechnologyGui]: Empty,
	[InputActionType.LaunchRocket]: Empty,
	[InputActionType.OpenProductionGui]: Empty,
	[InputActionType.StopRepair]: Empty,
	[InputActionType.CancelNewBlueprint]: Empty,
	[InputActionType.CloseBlueprintRecord]: Empty,
	[InputActionType.CopyEntitySettings]: Empty,
	[InputActionType.PasteEntitySettings]: Empty,
	[InputActionType.DestroyOpenedItem]: Empty,
	[InputActionType.CopyOpenedItem]: Empty,
	[InputActionType.ToggleShowEntityInfo]: Empty,
	[InputActionType.SingleplayerInit]: Empty,
	[InputActionType.MultiplayerInit]: Empty,
	[InputActionType.DisconnectAllPlayers]: Empty,
	[InputActionType.SwitchToRenameStopGui]: Empty,
	[InputActionType.OpenBonusGui]: Empty,
	[InputActionType.OpenTrainsGui]: Empty,
	[InputActionType.OpenAchievementsGui]: Empty,
	[InputActionType.CycleBlueprintBookForwards]: Empty,
	[InputActionType.CycleBlueprintBookBackwards]: Empty,
	[InputActionType.CycleClipboardForwards]: Empty,
	[InputActionType.CycleClipboardBackwards]: Empty,
	[InputActionType.StopMovementInTheNextTick]: Empty,
	[InputActionType.ToggleEnableVehicleLogisticsWhileMoving]: Empty,
	[InputActionType.ToggleDeconstructionItemEntityFilterMode]: Empty,
	[InputActionType.ToggleDeconstructionItemTileFilterMode]: Empty,
	[InputActionType.OpenLogisticGui]: Empty,
	[InputActionType.SelectNextValidGun]: Empty,
	[InputActionType.ToggleMapEditor]: Empty,
	[InputActionType.DeleteBlueprintLibrary]: Empty,
	[InputActionType.GameCreatedFromScenario]: Empty,
	[InputActionType.ActivateCopy]: Empty,
	[InputActionType.ActivateCut]: Empty,
	[InputActionType.ActivatePaste]: Empty,
	[InputActionType.Undo]: Empty,
	[InputActionType.TogglePersonalRoboport]: Empty,
	[InputActionType.ToggleEquipmentMovementBonus]: Empty,
	[InputActionType.TogglePersonalLogisticRequests]: Empty,
	[InputActionType.ToggleEntityLogisticRequests]: Empty,
	[InputActionType.StopBuildingByMoving]: Empty,
	[InputActionType.FlushOpenedEntityFluid]: Empty,
	[InputActionType.ForceFullCRC]: Empty,

	[InputActionType.OpenTipsAndTricksGui]: NotImplemented,
	[InputActionType.OpenBlueprintLibraryGui]: NotImplemented,
	[InputActionType.ChangeBlueprintLibraryTab]: NotImplemented,
	[InputActionType.DropItem]: NotImplemented,
	[InputActionType.Build]: NotImplemented,
	[InputActionType.StartWalking]: Direction,
	[InputActionType.BeginMiningTerrain]: NotImplemented,
	[InputActionType.ChangeRidingState]: NotImplemented,
	[InputActionType.OpenItem]: NotImplemented,
	[InputActionType.OpenParentOfOpenedItem]: NotImplemented,
	[InputActionType.ResetItem]: NotImplemented,
	[InputActionType.DestroyItem]: NotImplemented,
	[InputActionType.OpenModItem]: NotImplemented,
	[InputActionType.OpenEquipment]: NotImplemented,
	[InputActionType.CursorTransfer]: NotImplemented,
	[InputActionType.CursorSplit]: NotImplemented,
	[InputActionType.StackTransfer]: NotImplemented,
	[InputActionType.InventoryTransfer]: NotImplemented,
	[InputActionType.CheckCRCHeuristic]: CrcData,
	[InputActionType.Craft]: NotImplemented,
	[InputActionType.WireDragging]: NotImplemented,
	[InputActionType.ChangeShootingState]: ShootingState,
	[InputActionType.SetupAssemblingMachine]: NotImplemented,
	[InputActionType.SelectedEntityChanged]: NotImplemented,
	[InputActionType.SmartPipette]: NotImplemented,
	[InputActionType.StackSplit]: NotImplemented,
	[InputActionType.InventorySplit]: NotImplemented,
	[InputActionType.CancelCraft]: NotImplemented,
	[InputActionType.SetFilter]: NotImplemented,
	[InputActionType.CheckCRC]: CrcData,
	[InputActionType.SetCircuitCondition]: NotImplemented,
	[InputActionType.SetSignal]: NotImplemented,
	[InputActionType.StartResearch]: NotImplemented,
	[InputActionType.SetLogisticFilterItem]: NotImplemented,
	[InputActionType.SetLogisticFilterSignal]: NotImplemented,
	[InputActionType.SetCircuitModeOfOperation]: NotImplemented,
	[InputActionType.GuiClick]: NotImplemented,
	[InputActionType.GuiConfirmed]: NotImplemented,
	[InputActionType.WriteToConsole]: NotImplemented,
	[InputActionType.MarketOffer]: NotImplemented,
	[InputActionType.AddTrainStation]: NotImplemented,
	[InputActionType.ChangeTrainStopStation]: NotImplemented,
	[InputActionType.ChangeActiveItemGroupForCrafting]: NotImplemented,
	[InputActionType.ChangeActiveItemGroupForFilters]: NotImplemented,
	[InputActionType.ChangeActiveCharacterTab]: NotImplemented,
	[InputActionType.GuiTextChanged]: NotImplemented,
	[InputActionType.GuiCheckedStateChanged]: NotImplemented,
	[InputActionType.GuiSelectionStateChanged]: NotImplemented,
	[InputActionType.GuiSelectedTabChanged]: NotImplemented,
	[InputActionType.GuiValueChanged]: NotImplemented,
	[InputActionType.GuiSwitchStateChanged]: NotImplemented,
	[InputActionType.GuiLocationChanged]: NotImplemented,
	[InputActionType.PlaceEquipment]: NotImplemented,
	[InputActionType.TakeEquipment]: NotImplemented,
	[InputActionType.UseItem]: NotImplemented,
	[InputActionType.SendSpidertron]: NotImplemented,
	[InputActionType.UseArtilleryRemote]: NotImplemented,
	[InputActionType.SetInventoryBar]: NotImplemented,
	[InputActionType.MoveOnZoom]: NotImplemented,
	[InputActionType.StartRepair]: NotImplemented,
	[InputActionType.Deconstruct]: NotImplemented,
	[InputActionType.Upgrade]: NotImplemented,
	[InputActionType.Copy]: NotImplemented,
	[InputActionType.AlternativeCopy]: NotImplemented,
	[InputActionType.SelectBlueprintEntities]: NotImplemented,
	[InputActionType.AltSelectBlueprintEntities]: NotImplemented,
	[InputActionType.SetupBlueprint]: NotImplemented,
	[InputActionType.SetupSingleBlueprintRecord]: NotImplemented,
	[InputActionType.CopyOpenedBlueprint]: NotImplemented,
	[InputActionType.ReassignBlueprint]: NotImplemented,
	[InputActionType.OpenBlueprintRecord]: NotImplemented,
	[InputActionType.GrabBlueprintRecord]: NotImplemented,
	[InputActionType.DropBlueprintRecord]: NotImplemented,
	[InputActionType.DeleteBlueprintRecord]: NotImplemented,
	[InputActionType.UpgradeOpenedBlueprintByRecord]: NotImplemented,
	[InputActionType.UpgradeOpenedBlueprintByItem]: NotImplemented,
	[InputActionType.SpawnItem]: NotImplemented,
	[InputActionType.SpawnItemStackTransfer]: NotImplemented,
	[InputActionType.UpdateBlueprintShelf]: NotImplemented,
	[InputActionType.TransferBlueprint]: NotImplemented,
	[InputActionType.TransferBlueprintImmediately]: NotImplemented,
	[InputActionType.EditBlueprintToolPreview]: NotImplemented,
	[InputActionType.RemoveCables]: NotImplemented,
	[InputActionType.ExportBlueprint]: NotImplemented,
	[InputActionType.ImportBlueprint]: NotImplemented,
	[InputActionType.ImportBlueprintsFiltered]: NotImplemented,
	[InputActionType.PlayerJoinGame]: PlayerJoinGameData,
	[InputActionType.PlayerAdminChange]: NotImplemented,
	[InputActionType.CancelDeconstruct]: NotImplemented,
	[InputActionType.CancelUpgrade]: NotImplemented,
	[InputActionType.ChangeArithmeticCombinatorParameters]: NotImplemented,
	[InputActionType.ChangeDeciderCombinatorParameters]: NotImplemented,
	[InputActionType.ChangeProgrammableSpeakerParameters]: NotImplemented,
	[InputActionType.ChangeProgrammableSpeakerAlertParameters]: NotImplemented,
	[InputActionType.ChangeProgrammableSpeakerCircuitParameters]: NotImplemented,
	[InputActionType.SetVehicleAutomaticTargetingParameters]: NotImplemented,
	[InputActionType.BuildTerrain]: NotImplemented,
	[InputActionType.ChangeTrainWaitCondition]: NotImplemented,
	[InputActionType.ChangeTrainWaitConditionData]: NotImplemented,
	[InputActionType.CustomInput]: NotImplemented,
	[InputActionType.ChangeItemLabel]: NotImplemented,
	[InputActionType.ChangeItemDescription]: NotImplemented,
	[InputActionType.ChangeEntityLabel]: NotImplemented,
	[InputActionType.BuildRail]: NotImplemented,
	[InputActionType.CancelResearch]: NotImplemented,
	[InputActionType.SelectArea]: NotImplemented,
	[InputActionType.AltSelectArea]: NotImplemented,
	[InputActionType.ReverseSelectArea]: NotImplemented,
	[InputActionType.ServerCommand]: ServerCommandData,
	[InputActionType.SetControllerLogisticTrashFilterItem]: NotImplemented,
	[InputActionType.SetEntityLogisticTrashFilterItem]: NotImplemented,
	[InputActionType.SetInfinityContainerFilterItem]: NotImplemented,
	[InputActionType.SetInfinityPipeFilter]: NotImplemented,
	[InputActionType.ModSettingsChanged]: NotImplemented,
	[InputActionType.SetEntityEnergyProperty]: NotImplemented,
	[InputActionType.EditCustomTag]: NotImplemented,
	[InputActionType.EditPermissionGroup]: NotImplemented,
	[InputActionType.ImportBlueprintString]: NotImplemented,
	[InputActionType.ImportPermissionsString]: NotImplemented,
	[InputActionType.ReloadScript]: NotImplemented,
	[InputActionType.ReloadScriptDataTooLarge]: NotImplemented,
	[InputActionType.GuiElemChanged]: NotImplemented,
	[InputActionType.BlueprintTransferQueueUpdate]: NotImplemented,
	[InputActionType.DragTrainSchedule]: NotImplemented,
	[InputActionType.DragTrainWaitCondition]: NotImplemented,
	[InputActionType.SelectItem]: NotImplemented,
	[InputActionType.SelectEntitySlot]: NotImplemented,
	[InputActionType.SelectTileSlot]: NotImplemented,
	[InputActionType.SelectMapperSlot]: NotImplemented,
	[InputActionType.DisplayResolutionChanged]: NotImplemented,
	[InputActionType.QuickBarSetSlot]: NotImplemented,
	[InputActionType.QuickBarPickSlot]: NotImplemented,
	[InputActionType.QuickBarSetSelectedPage]: NotImplemented,
	[InputActionType.PlayerLeaveGame]: DisconnectReason,
	[InputActionType.MapEditorAction]: NotImplemented,
	[InputActionType.PutSpecialItemInMap]: NotImplemented,
	[InputActionType.PutSpecialRecordInMap]: NotImplemented,
	[InputActionType.ChangeMultiplayerConfig]: NotImplemented,
	[InputActionType.AdminAction]: NotImplemented,
	[InputActionType.LuaShortcut]: NotImplemented,
	[InputActionType.TranslateString]: NotImplemented,
	[InputActionType.FlushOpenedEntitySpecificFluid]: NotImplemented,
	[InputActionType.ChangePickingState]: NotImplemented,
	[InputActionType.SelectedEntityChangedVeryClose]: number,
	[InputActionType.SelectedEntityChangedVeryClosePrecise]: number,
	[InputActionType.SelectedEntityChangedRelative]: number,
	[InputActionType.SelectedEntityChangedBasedOnUnitNumber]: number,
	[InputActionType.SetAutosortInventory]: NotImplemented,
	[InputActionType.SetFlatControllerGui]: NotImplemented,
	[InputActionType.SetRecipeNotifications]: NotImplemented,
	[InputActionType.SetAutoLaunchRocket]: NotImplemented,
	[InputActionType.SwitchConstantCombinatorState]: NotImplemented,
	[InputActionType.SwitchPowerSwitchState]: NotImplemented,
	[InputActionType.SwitchInserterFilterModeState]: NotImplemented,
	[InputActionType.SwitchConnectToLogisticNetwork]: NotImplemented,
	[InputActionType.SetBehaviorMode]: NotImplemented,
	[InputActionType.FastEntityTransfer]: NotImplemented,
	[InputActionType.RotateEntity]: NotImplemented,
	[InputActionType.FastEntitySplit]: NotImplemented,
	[InputActionType.SetTrainStopped]: NotImplemented,
	[InputActionType.ChangeControllerSpeed]: NotImplemented,
	[InputActionType.SetAllowCommands]: NotImplemented,
	[InputActionType.SetResearchFinishedStopsGame]: NotImplemented,
	[InputActionType.SetInserterMaxStackSize]: NotImplemented,
	[InputActionType.OpenTrainGui]: NotImplemented,
	[InputActionType.SetEntityColor]: NotImplemented,
	[InputActionType.SetDeconstructionItemTreesAndRocksOnly]: NotImplemented,
	[InputActionType.SetDeconstructionItemTileSelectionMode]: NotImplemented,
	[InputActionType.DeleteCustomTag]: NotImplemented,
	[InputActionType.DeletePermissionGroup]: NotImplemented,
	[InputActionType.AddPermissionGroup]: NotImplemented,
	[InputActionType.SetInfinityContainerRemoveUnfilteredItems]: NotImplemented,
	[InputActionType.SetCarWeaponsControl]: NotImplemented,
	[InputActionType.SetRequestFromBuffers]: NotImplemented,
	[InputActionType.ChangeActiveQuickBar]: NotImplemented,
	[InputActionType.OpenPermissionsGui]: NotImplemented,
	[InputActionType.DisplayScaleChanged]: NotImplemented,
	[InputActionType.SetSplitterPriority]: NotImplemented,
	[InputActionType.GrabInternalBlueprintFromText]: NotImplemented,
	[InputActionType.SetHeatInterfaceTemperature]: NotImplemented,
	[InputActionType.SetHeatInterfaceMode]: NotImplemented,
	[InputActionType.OpenTrainStationGui]: NotImplemented,
	[InputActionType.RemoveTrainStation]: NotImplemented,
	[InputActionType.GoToTrainStation]: NotImplemented,
	[InputActionType.RenderModeChanged]: NotImplemented,
	[InputActionType.SetPlayerColor]: NotImplemented,
	[InputActionType.PlayerClickedGpsTag]: NotImplemented,
	[InputActionType.SetTrainsLimit]: NotImplemented,
	[InputActionType.ClearRecipeNotification]: NotImplemented,
	[InputActionType.SetLinkedContainerLinkID]: NotImplemented,
};

const inputActionDuplex: DuplexerLookupTable<InputActionType, InputActionValueType> = {
	[InputActionType.Nothing]: Empty,
	[InputActionType.StopWalking]: Empty,
	[InputActionType.BeginMining]: Empty,
	[InputActionType.StopMining]: Empty,
	[InputActionType.ToggleDriving]: Empty,
	[InputActionType.OpenGui]: Empty,
	[InputActionType.CloseGui]: Empty,
	[InputActionType.OpenCharacterGui]: Empty,
	[InputActionType.OpenCurrentVehicleGui]: Empty,
	[InputActionType.ConnectRollingStock]: Empty,
	[InputActionType.DisconnectRollingStock]: Empty,
	[InputActionType.SelectedEntityCleared]: Empty,
	[InputActionType.ClearCursor]: Empty,
	[InputActionType.ResetAssemblingMachine]: Empty,
	[InputActionType.OpenTechnologyGui]: Empty,
	[InputActionType.LaunchRocket]: Empty,
	[InputActionType.OpenProductionGui]: Empty,
	[InputActionType.StopRepair]: Empty,
	[InputActionType.CancelNewBlueprint]: Empty,
	[InputActionType.CloseBlueprintRecord]: Empty,
	[InputActionType.CopyEntitySettings]: Empty,
	[InputActionType.PasteEntitySettings]: Empty,
	[InputActionType.DestroyOpenedItem]: Empty,
	[InputActionType.CopyOpenedItem]: Empty,
	[InputActionType.ToggleShowEntityInfo]: Empty,
	[InputActionType.SingleplayerInit]: Empty,
	[InputActionType.MultiplayerInit]: Empty,
	[InputActionType.DisconnectAllPlayers]: Empty,
	[InputActionType.SwitchToRenameStopGui]: Empty,
	[InputActionType.OpenBonusGui]: Empty,
	[InputActionType.OpenTrainsGui]: Empty,
	[InputActionType.OpenAchievementsGui]: Empty,
	[InputActionType.CycleBlueprintBookForwards]: Empty,
	[InputActionType.CycleBlueprintBookBackwards]: Empty,
	[InputActionType.CycleClipboardForwards]: Empty,
	[InputActionType.CycleClipboardBackwards]: Empty,
	[InputActionType.StopMovementInTheNextTick]: Empty,
	[InputActionType.ToggleEnableVehicleLogisticsWhileMoving]: Empty,
	[InputActionType.ToggleDeconstructionItemEntityFilterMode]: Empty,
	[InputActionType.ToggleDeconstructionItemTileFilterMode]: Empty,
	[InputActionType.OpenLogisticGui]: Empty,
	[InputActionType.SelectNextValidGun]: Empty,
	[InputActionType.ToggleMapEditor]: Empty,
	[InputActionType.DeleteBlueprintLibrary]: Empty,
	[InputActionType.GameCreatedFromScenario]: Empty,
	[InputActionType.ActivateCopy]: Empty,
	[InputActionType.ActivateCut]: Empty,
	[InputActionType.ActivatePaste]: Empty,
	[InputActionType.Undo]: Empty,
	[InputActionType.TogglePersonalRoboport]: Empty,
	[InputActionType.ToggleEquipmentMovementBonus]: Empty,
	[InputActionType.TogglePersonalLogisticRequests]: Empty,
	[InputActionType.ToggleEntityLogisticRequests]: Empty,
	[InputActionType.StopBuildingByMoving]: Empty,
	[InputActionType.FlushOpenedEntityFluid]: Empty,
	[InputActionType.ForceFullCRC]: Empty,

	[InputActionType.OpenTipsAndTricksGui]: NotImplemented,
	[InputActionType.OpenBlueprintLibraryGui]: NotImplemented,
	[InputActionType.ChangeBlueprintLibraryTab]: NotImplemented,
	[InputActionType.DropItem]: NotImplemented,
	[InputActionType.Build]: NotImplemented,
	[InputActionType.StartWalking]: Direction,
	[InputActionType.BeginMiningTerrain]: NotImplemented,
	[InputActionType.ChangeRidingState]: NotImplemented,
	[InputActionType.OpenItem]: NotImplemented,
	[InputActionType.OpenParentOfOpenedItem]: NotImplemented,
	[InputActionType.ResetItem]: NotImplemented,
	[InputActionType.DestroyItem]: NotImplemented,
	[InputActionType.OpenModItem]: NotImplemented,
	[InputActionType.OpenEquipment]: NotImplemented,
	[InputActionType.CursorTransfer]: NotImplemented,
	[InputActionType.CursorSplit]: NotImplemented,
	[InputActionType.StackTransfer]: NotImplemented,
	[InputActionType.InventoryTransfer]: NotImplemented,
	[InputActionType.CheckCRCHeuristic]: CrcData,
	[InputActionType.Craft]: NotImplemented,
	[InputActionType.WireDragging]: NotImplemented,
	[InputActionType.ChangeShootingState]: ShootingState,
	[InputActionType.SetupAssemblingMachine]: NotImplemented,
	[InputActionType.SelectedEntityChanged]: NotImplemented,
	[InputActionType.SmartPipette]: NotImplemented,
	[InputActionType.StackSplit]: NotImplemented,
	[InputActionType.InventorySplit]: NotImplemented,
	[InputActionType.CancelCraft]: NotImplemented,
	[InputActionType.SetFilter]: NotImplemented,
	[InputActionType.CheckCRC]: CrcData,
	[InputActionType.SetCircuitCondition]: NotImplemented,
	[InputActionType.SetSignal]: NotImplemented,
	[InputActionType.StartResearch]: NotImplemented,
	[InputActionType.SetLogisticFilterItem]: NotImplemented,
	[InputActionType.SetLogisticFilterSignal]: NotImplemented,
	[InputActionType.SetCircuitModeOfOperation]: NotImplemented,
	[InputActionType.GuiClick]: NotImplemented,
	[InputActionType.GuiConfirmed]: NotImplemented,
	[InputActionType.WriteToConsole]: NotImplemented,
	[InputActionType.MarketOffer]: NotImplemented,
	[InputActionType.AddTrainStation]: NotImplemented,
	[InputActionType.ChangeTrainStopStation]: NotImplemented,
	[InputActionType.ChangeActiveItemGroupForCrafting]: NotImplemented,
	[InputActionType.ChangeActiveItemGroupForFilters]: NotImplemented,
	[InputActionType.ChangeActiveCharacterTab]: NotImplemented,
	[InputActionType.GuiTextChanged]: NotImplemented,
	[InputActionType.GuiCheckedStateChanged]: NotImplemented,
	[InputActionType.GuiSelectionStateChanged]: NotImplemented,
	[InputActionType.GuiSelectedTabChanged]: NotImplemented,
	[InputActionType.GuiValueChanged]: NotImplemented,
	[InputActionType.GuiSwitchStateChanged]: NotImplemented,
	[InputActionType.GuiLocationChanged]: NotImplemented,
	[InputActionType.PlaceEquipment]: NotImplemented,
	[InputActionType.TakeEquipment]: NotImplemented,
	[InputActionType.UseItem]: NotImplemented,
	[InputActionType.SendSpidertron]: NotImplemented,
	[InputActionType.UseArtilleryRemote]: NotImplemented,
	[InputActionType.SetInventoryBar]: NotImplemented,
	[InputActionType.MoveOnZoom]: NotImplemented,
	[InputActionType.StartRepair]: NotImplemented,
	[InputActionType.Deconstruct]: NotImplemented,
	[InputActionType.Upgrade]: NotImplemented,
	[InputActionType.Copy]: NotImplemented,
	[InputActionType.AlternativeCopy]: NotImplemented,
	[InputActionType.SelectBlueprintEntities]: NotImplemented,
	[InputActionType.AltSelectBlueprintEntities]: NotImplemented,
	[InputActionType.SetupBlueprint]: NotImplemented,
	[InputActionType.SetupSingleBlueprintRecord]: NotImplemented,
	[InputActionType.CopyOpenedBlueprint]: NotImplemented,
	[InputActionType.ReassignBlueprint]: NotImplemented,
	[InputActionType.OpenBlueprintRecord]: NotImplemented,
	[InputActionType.GrabBlueprintRecord]: NotImplemented,
	[InputActionType.DropBlueprintRecord]: NotImplemented,
	[InputActionType.DeleteBlueprintRecord]: NotImplemented,
	[InputActionType.UpgradeOpenedBlueprintByRecord]: NotImplemented,
	[InputActionType.UpgradeOpenedBlueprintByItem]: NotImplemented,
	[InputActionType.SpawnItem]: NotImplemented,
	[InputActionType.SpawnItemStackTransfer]: NotImplemented,
	[InputActionType.UpdateBlueprintShelf]: NotImplemented,
	[InputActionType.TransferBlueprint]: NotImplemented,
	[InputActionType.TransferBlueprintImmediately]: NotImplemented,
	[InputActionType.EditBlueprintToolPreview]: NotImplemented,
	[InputActionType.RemoveCables]: NotImplemented,
	[InputActionType.ExportBlueprint]: NotImplemented,
	[InputActionType.ImportBlueprint]: NotImplemented,
	[InputActionType.ImportBlueprintsFiltered]: NotImplemented,
	[InputActionType.PlayerJoinGame]: PlayerJoinGameData,
	[InputActionType.PlayerAdminChange]: NotImplemented,
	[InputActionType.CancelDeconstruct]: NotImplemented,
	[InputActionType.CancelUpgrade]: NotImplemented,
	[InputActionType.ChangeArithmeticCombinatorParameters]: NotImplemented,
	[InputActionType.ChangeDeciderCombinatorParameters]: NotImplemented,
	[InputActionType.ChangeProgrammableSpeakerParameters]: NotImplemented,
	[InputActionType.ChangeProgrammableSpeakerAlertParameters]: NotImplemented,
	[InputActionType.ChangeProgrammableSpeakerCircuitParameters]: NotImplemented,
	[InputActionType.SetVehicleAutomaticTargetingParameters]: NotImplemented,
	[InputActionType.BuildTerrain]: NotImplemented,
	[InputActionType.ChangeTrainWaitCondition]: NotImplemented,
	[InputActionType.ChangeTrainWaitConditionData]: NotImplemented,
	[InputActionType.CustomInput]: NotImplemented,
	[InputActionType.ChangeItemLabel]: NotImplemented,
	[InputActionType.ChangeItemDescription]: NotImplemented,
	[InputActionType.ChangeEntityLabel]: NotImplemented,
	[InputActionType.BuildRail]: NotImplemented,
	[InputActionType.CancelResearch]: NotImplemented,
	[InputActionType.SelectArea]: NotImplemented,
	[InputActionType.AltSelectArea]: NotImplemented,
	[InputActionType.ReverseSelectArea]: NotImplemented,
	[InputActionType.ServerCommand]: ServerCommandData,
	[InputActionType.SetControllerLogisticTrashFilterItem]: NotImplemented,
	[InputActionType.SetEntityLogisticTrashFilterItem]: NotImplemented,
	[InputActionType.SetInfinityContainerFilterItem]: NotImplemented,
	[InputActionType.SetInfinityPipeFilter]: NotImplemented,
	[InputActionType.ModSettingsChanged]: NotImplemented,
	[InputActionType.SetEntityEnergyProperty]: NotImplemented,
	[InputActionType.EditCustomTag]: NotImplemented,
	[InputActionType.EditPermissionGroup]: NotImplemented,
	[InputActionType.ImportBlueprintString]: NotImplemented,
	[InputActionType.ImportPermissionsString]: NotImplemented,
	[InputActionType.ReloadScript]: NotImplemented,
	[InputActionType.ReloadScriptDataTooLarge]: NotImplemented,
	[InputActionType.GuiElemChanged]: NotImplemented,
	[InputActionType.BlueprintTransferQueueUpdate]: NotImplemented,
	[InputActionType.DragTrainSchedule]: NotImplemented,
	[InputActionType.DragTrainWaitCondition]: NotImplemented,
	[InputActionType.SelectItem]: NotImplemented,
	[InputActionType.SelectEntitySlot]: NotImplemented,
	[InputActionType.SelectTileSlot]: NotImplemented,
	[InputActionType.SelectMapperSlot]: NotImplemented,
	[InputActionType.DisplayResolutionChanged]: NotImplemented,
	[InputActionType.QuickBarSetSlot]: NotImplemented,
	[InputActionType.QuickBarPickSlot]: NotImplemented,
	[InputActionType.QuickBarSetSelectedPage]: NotImplemented,
	[InputActionType.PlayerLeaveGame]: UInt8,
	[InputActionType.MapEditorAction]: NotImplemented,
	[InputActionType.PutSpecialItemInMap]: NotImplemented,
	[InputActionType.PutSpecialRecordInMap]: NotImplemented,
	[InputActionType.ChangeMultiplayerConfig]: NotImplemented,
	[InputActionType.AdminAction]: NotImplemented,
	[InputActionType.LuaShortcut]: NotImplemented,
	[InputActionType.TranslateString]: NotImplemented,
	[InputActionType.FlushOpenedEntitySpecificFluid]: NotImplemented,
	[InputActionType.ChangePickingState]: NotImplemented,
	[InputActionType.SelectedEntityChangedVeryClose]: UInt8,
	[InputActionType.SelectedEntityChangedVeryClosePrecise]: UInt16,
	[InputActionType.SelectedEntityChangedRelative]: UInt32,
	[InputActionType.SelectedEntityChangedBasedOnUnitNumber]: UInt32,
	[InputActionType.SetAutosortInventory]: NotImplemented,
	[InputActionType.SetFlatControllerGui]: NotImplemented,
	[InputActionType.SetRecipeNotifications]: NotImplemented,
	[InputActionType.SetAutoLaunchRocket]: NotImplemented,
	[InputActionType.SwitchConstantCombinatorState]: NotImplemented,
	[InputActionType.SwitchPowerSwitchState]: NotImplemented,
	[InputActionType.SwitchInserterFilterModeState]: NotImplemented,
	[InputActionType.SwitchConnectToLogisticNetwork]: NotImplemented,
	[InputActionType.SetBehaviorMode]: NotImplemented,
	[InputActionType.FastEntityTransfer]: NotImplemented,
	[InputActionType.RotateEntity]: NotImplemented,
	[InputActionType.FastEntitySplit]: NotImplemented,
	[InputActionType.SetTrainStopped]: NotImplemented,
	[InputActionType.ChangeControllerSpeed]: NotImplemented,
	[InputActionType.SetAllowCommands]: NotImplemented,
	[InputActionType.SetResearchFinishedStopsGame]: NotImplemented,
	[InputActionType.SetInserterMaxStackSize]: NotImplemented,
	[InputActionType.OpenTrainGui]: NotImplemented,
	[InputActionType.SetEntityColor]: NotImplemented,
	[InputActionType.SetDeconstructionItemTreesAndRocksOnly]: NotImplemented,
	[InputActionType.SetDeconstructionItemTileSelectionMode]: NotImplemented,
	[InputActionType.DeleteCustomTag]: NotImplemented,
	[InputActionType.DeletePermissionGroup]: NotImplemented,
	[InputActionType.AddPermissionGroup]: NotImplemented,
	[InputActionType.SetInfinityContainerRemoveUnfilteredItems]: NotImplemented,
	[InputActionType.SetCarWeaponsControl]: NotImplemented,
	[InputActionType.SetRequestFromBuffers]: NotImplemented,
	[InputActionType.ChangeActiveQuickBar]: NotImplemented,
	[InputActionType.OpenPermissionsGui]: NotImplemented,
	[InputActionType.DisplayScaleChanged]: NotImplemented,
	[InputActionType.SetSplitterPriority]: NotImplemented,
	[InputActionType.GrabInternalBlueprintFromText]: NotImplemented,
	[InputActionType.SetHeatInterfaceTemperature]: NotImplemented,
	[InputActionType.SetHeatInterfaceMode]: NotImplemented,
	[InputActionType.OpenTrainStationGui]: NotImplemented,
	[InputActionType.RemoveTrainStation]: NotImplemented,
	[InputActionType.GoToTrainStation]: NotImplemented,
	[InputActionType.RenderModeChanged]: NotImplemented,
	[InputActionType.SetPlayerColor]: NotImplemented,
	[InputActionType.PlayerClickedGpsTag]: NotImplemented,
	[InputActionType.SetTrainsLimit]: NotImplemented,
	[InputActionType.ClearRecipeNotification]: NotImplemented,
	[InputActionType.SetLinkedContainerLinkID]: NotImplemented,
};

export class InputAction<T extends InputActionType = InputActionType> {
	constructor(
		public type: T,
		public data: InputActionValueType[T],
		// For convenience when creating actions to send the playerIndex can
		// be left out which will cause FactorioClient.sendInTickClosure
		// to set it to the client's playerIndex
		public playerIndex?: number,
	) { }

	static read(stream: Readable, lastPlayerIndex: number = 0) {
		const type = UInt8.read(stream);
		return this.readPayload(stream, type, lastPlayerIndex);
	}

	static readPayload(stream: Readable, type: InputActionType, lastPlayerIndex: number = 0) {
		const playerIndex = (SpaceOptimizedUInt16.read(stream) + lastPlayerIndex) & 0xffff;

		const duplex = inputActionDuplex[type];
		if (duplex === NotImplemented) {
			throw new DecodeError(
				`Unknown input action ${InputActionType[type]} (${type})`,
				{ stream, inputActionType: type },
			);
		}

		return new InputAction(
			type,
			duplex.read(stream),
			playerIndex,
		);
	}

	static write(stream: Writable, input: InputAction, lastPlayerIndex: number) {
		UInt8.write(stream, input.type);
		this.writePayload(stream, input, lastPlayerIndex);
	}

	static writePayload<T extends InputActionType>(
		stream: Writable, input: InputAction<T>, lastPlayerIndex: number
	) {
		SpaceOptimizedUInt16.write(stream, input.playerIndex! - lastPlayerIndex & 0xffff);
		const duplex = inputActionDuplex[input.type];
		if (duplex as unknown === NotImplemented) {
			throw new EncodeError(
				`Unknown input action ${InputActionType[input.type]} (${input.type})`,
				{ stream, target: input },
			);
		}

		duplex.write(stream, input.data);
	}
}


export class InputActionSegment {
	constructor(
		public type: InputActionType,
		public id: number,
		public playerIndex: number,
		public totalSegments: number,
		public segmentNumber: number,
		public payload: Buffer,
	) { }

	static read(stream: Readable) {
		return new InputActionSegment(
			UInt8.read(stream),
			UInt32.read(stream),
			SpaceOptimizedUInt16.read(stream),
			SpaceOptimizedUInt32.read(stream),
			SpaceOptimizedUInt32.read(stream),
			StringT.read(stream),
		);
	}

	static write(stream: Writable, segment: InputActionSegment) {
		UInt8.write(stream, segment.type);
		UInt32.write(stream, segment.id);
		SpaceOptimizedUInt16.write(stream, segment.playerIndex);
		SpaceOptimizedUInt32.write(stream, segment.totalSegments);
		SpaceOptimizedUInt32.write(stream, segment.segmentNumber);
		StringT.write(stream, segment.payload);
	}
}
